### ISSUE TITLE
ecs container error(maybe)

### ISSUE THREAD

**Issue by jinseo-jang** [aws-samples/asynchronous-messaging-workshop#1]
in LAB-1-9.Test fan-out&messaging filter, I found out that ecs task came across error like the below. 
can you check out reason for this when you get a chance?
```
2020-03-19T14:02:09.868+09:00 | INFO:web:
-- | --
  | 2020-03-19T14:02:09.868+09:00 | processing message: {"from": "Berlin", "to": "Frankfurt", "duration": 420, "distance": 600, "customer": "cmr", "fare": 256.5, "id": "c1e00329-188d-4f81-b741-dc7e367a077e"} ...
  | 2020-03-19T14:02:09.868+09:00 | ERROR:web:Exception on / [POST]
  | 2020-03-19T14:02:09.868+09:00 | Traceback (most recent call last):
  | 2020-03-19T14:02:09.868+09:00 | File "/usr/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
  | 2020-03-19T14:02:09.868+09:00 | response = self.full_dispatch_request()
  | 2020-03-19T14:02:09.868+09:00 | File "/usr/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
  | 2020-03-19T14:02:09.868+09:00 | rv = self.handle_user_exception(e)
  | 2020-03-19T14:02:09.868+09:00 | File "/usr/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
  | 2020-03-19T14:02:09.868+09:00 | reraise(exc_type, exc_value, tb)
  | 2020-03-19T14:02:09.868+09:00 | File "/usr/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
  | 2020-03-19T14:02:09.868+09:00 | rv = self.dispatch_request()
  | 2020-03-19T14:02:09.868+09:00 | File "/usr/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
  | 2020-03-19T14:02:09.868+09:00 | return self.view_functions[rule.endpoint](**req.view_args)
  | 2020-03-19T14:02:09.868+09:00 | File "/app/web/__init__.py", line 45, in index
  | 2020-03-19T14:02:09.868+09:00 | message = json.loads(data)['Message']
  | 2020-03-19T14:02:09.868+09:00 | KeyError: 'Message'
  | 2020-03-19T14:02:09.868+09:00 | INFO:werkzeug:10.11.0.170 - - [19/Mar/2020 05:02:09] "POST / HTTP/1.1" 500 -
  | 2020-03-19T14:02:27.246+09:00 | INFO:werkzeug:10.11.1.82 - - [19/Mar/2020 05:02:27] "GET / HTTP/1.1" 200 -


```

**Comment by sliedig** [comment]
Resolved in PR #19
